# Generated by Django 4.2 on 2023-04-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='patient_ID',
            field=models.CharField(blank=True, default='CUST686', max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('T', 'Terapist'), ('A', 'Assistence'), ('P', 'Patient'), ('R', 'Receptionist'), ('ADM', 'Admin')], max_length=3),
        ),
    ]
