# Generated by Django 4.2 on 2023-05-01 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patientregistration_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_receptionist',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patient.patientregistration'),
        ),
        migrations.AlterField(
            model_name='appointment_receptionist',
            name='patient_id_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointment_receptionist',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientbill',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientbill',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientbillbycustomer', to='patient.patientregistration'),
        ),
        migrations.AlterField(
            model_name='patientbill',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='patient_ID',
            field=models.CharField(blank=True, default='CUST747', max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prescription_physiotherapy_assistant',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistance_prescription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription_physiotherapy_assistant',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescription', to='patient.patientregistration'),
        ),
        migrations.AlterField(
            model_name='prescription_physiotherapy_assistant',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription_physiotherapy_assistant',
            name='symptoms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prescription_therapist',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription_therapist',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription_therapist',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription_therapist',
            name='symptoms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prescription_therapist',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_prescription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('T', 'Terapist'), ('A', 'Assistence'), ('R', 'Receptionist'), ('ADM', 'Admin')], max_length=3),
        ),
    ]
