# Generated by Django 4.2 on 2023-05-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_appointment_receptionist_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='MEDIA'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='patient_ID',
            field=models.CharField(blank=True, default='CUST991', max_length=70, primary_key=True, serialize=False),
        ),
    ]
