# Generated by Django 4.2 on 2023-05-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_user_image_alter_patientregistration_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='patient_ID',
            field=models.CharField(blank=True, default='CUST251', max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Terapist', 'Terapist'), ('Assistence', 'Assistence'), ('Receptionist', 'Receptionist'), ('Admin', 'Admin')], max_length=40),
        ),
    ]
