# Generated by Django 4.2 on 2023-05-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_patientregistration_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='patient_ID',
            field=models.CharField(blank=True, default='CUST601', max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='MEDIA'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Terapist', 'Terapist'), ('Assistence', 'Assistence'), ('Receptionist', 'Receptionist'), ('Admin', 'Admin')], max_length=40, null=True),
        ),
    ]
