# Generated by Django 4.2 on 2023-05-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_remove_user_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='patient_ID',
            field=models.CharField(blank=True, max_length=70, primary_key=True, serialize=False),
        ),
    ]
