# Generated by Django 4.2 on 2023-05-15 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_patientregistration_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_receptionist',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment_receptionist',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment_receptionist',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
